name: Daily PR Update

on:
  workflow_call:
        inputs:
          prDetails:
            description: "Pull Request details to be sent as a notification"
            required: true
            type: string

jobs:
  pr-update:
    runs-on: ubuntu-latest
    steps:

      - name: Send message to Slack
        env:
          TEXT: ${{ inputs.prDetails }}
          WH_URL: ${{ secrets.SLACK_DM_URL }}
        run: |
          # Remove surrounding quotes and escape internal double quotes in TEXT
          ESCAPED_TEXT=$(echo "$TEXT" | sed 's/^"//;s/"$//' | sed 's/"/\\"/g')
          # Use the escaped TEXT in the curl command
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"DAILY UPDATE \n$ESCAPED_TEXT\"}" "$WH_URL"