name: Daily PR Update

on:
  workflow_call:
    inputs:
      prDetails:
        description: "Pull Request details to be sent as a notification"
        required: true
        type: string

jobs:
  pr-update:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Send message to Slack
        env:
          TEXT: ${{ inputs.prDetails }}
          WH_URL: ${{ secrets.SLACK_DM_URL }}
        run: |
          # Debug: Print the WH_URL (partially masked for security)
          echo "Webhook URL: ${WH_URL:0:5}********"

          # Remove surrounding quotes and escape internal double quotes in TEXT
          ESCAPED_TEXT=$(echo "$TEXT" | sed 's/^"//;s/"$//' | sed 's/"/\\"/g')

          # Create JSON payload using jq
          JSON_PAYLOAD=$(jq -nc --arg text "$ESCAPED_TEXT" '{"text": $text}')

          # Debug: Print the JSON payload
          echo "JSON Payload: $JSON_PAYLOAD"

          # Use the JSON payload in the curl command
          curl -X POST -H 'Content-type: application/json' --data "DAILY UPDATE \n $JSON_PAYLOAD" "$WH_URL"
