name: Review Pipeline

on:
  pull_request:
    types: [review_requested]

  pull_request_review:
    types: [submitted]
permissions:
  contents: read
  pull-requests: write
jobs:
  pr-auto-labeler:
    name: Labels
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_pr_labeler.yaml@main
    secrets: inherit
  review-control:
    name: Handler
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_slack_review_notifications.yaml@main
    secrets: inherit
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
