name: Review Pipeline

on:
  pull_request:
    types: [review_requested, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]
permissions:
  contents: read
  pull-requests: write
jobs:
  pr-auto-labeler:
    name: Labels
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_pr_labeler.yaml@main
    secrets: inherit
  review-control:
    name: Handler
    needs: pr-auto-labeler
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_slack_review_notifications.yaml@main
    secrets: inherit
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
