name: Review Pipeline

on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [review_requested]
  issue_comment:
    types: [created]
jobs:
  review-control:
    name: Handler
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_slack_review_notifications.yaml@main
    secrets: inherit
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      codeowners_path: StuartH1/testing-reusable-workflow/.github/CODEOWNERS
