name: Ping Notification

on:
  workflow_dispatch:

jobs:
  Message:
    runs-on: ubuntu-20.04
    steps:
      - name: message info
        id: message
        run: |
          # "firstword=testing" >> $GITHUB_OUTPUT
          echo "::set-output name=message::$(echo hello)"
    outputs: 
      message: ${{ steps.message.outputs.message }}
  Notification:
    name: Notification
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_test.yaml@main
    secrets: inherit
    with:
      message: ${{ needs.Message.outputs.message }}