name: Ping Notification

on:
  workflow_dispatch:

jobs:
  Message:
    runs-on: ubuntu-20.04
    steps:
      - name: message info
        id: message
        run: |
          echo "message=hello" >> $GITHUB_ENV
    outputs: 
      message: ${{ steps.message.outputs.message }}

  Notification:
    needs: Message
    name: Notification
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_test.yaml@main
    secrets: inherit
    with:
      message: ${{ needs.Message.outputs.message }}
