name: Ping Notification

on:
  workflow_dispatch:

jobs:
  Message:
    runs-on: ubuntu-20.04
    steps:
      - name: Set message output
        run: echo "message=Hello from Ping Notification Workflow" >> $GITHUB_OUTPUT
    outputs: 
      message: ${{ steps.Message.outputs.message }}

  Notification:
    needs: [Message]
    uses: StuartH1/Reusable-Workflow/.github/workflows/reusable_test.yaml@main
    secrets: inherit
    with:
      message: ${{ needs.Message.outputs.message }}
